spring.application.name=agileagent
spring.ai.openai.api-key=
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-2.5-flash
#spring.ai.vectorstore.chroma.embedded=false
#spring.ai.vectorstore.chroma.api.base-url=http://localhost:8000/api/v2
#spring.ai.vectorstore.chroma.database-dir=./chroma-data
#spring.ai.vectorstore.chroma.collection-name=agile-agent
#spring.ai.vectorstore.chroma.client.create-collection-on-start=true